### ISSUE TITLE
Build Error ,symbol not found fi.iki.elonen.NanoHTTPD

### ISSUE THREAD

**Issue by gavim6249** [ClaspTV/Vizbeee-AndroidTV-Install-Service#1]
I did the following steps
1. copy Android.bp, nanohttpd.jar to folder prebuilts/misc/common/nanohttpd/
2. copy AssistHttpServer.java, AssistService.java, AssistServiceManager.java
   to /frameworks/base/core/java/android/app/
3. modify frameworks/base/services/core/Android.bp
4. modify frameworks/base/core/res/AndroidManifest.xml
5.  Context.java cannot be modified directly
    system notifies me to use "make api-stubs-docs-non-updatable-update-current-api" 
    after "make api-stubs-docs-non-updatable-update-current-api”, we get new Context.java file
   frameworks/base/core/java/android/content/Context.java
6  modify frameworks/base/services/java/com/android/server/SystemServer.java
7. modify frameworks/base/core/api/current.txt

8 make -j32 , Get Build error , 
f**rameworks/base/core/java/android/app/AssistHttpServer.java:20: error: symbol not found fi.iki.elonen.NanoHTTPD**
Any other suggestions?

**Comment by gavim6249** [comment]
![BuildError](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/d1b944ec-873e-4ac4-9f51-1d92a95ffa88)

**Comment by gavim6249** [comment]
![Context_Java](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/744930d0-8368-40e7-89ef-51310d877218)

**Comment by Raasesh-Vizbee** [comment]
@gavim6249  This issue seems to arise when there are problems with the correct import of the nanohttpd library via the Android.bp file. We would appreciate it if you could verify that the steps outlined in System Service documentation (https://github.com/ClaspTV/ASSIST-Service/blob/master/README.md), specifically Step 3, have been accurately followed to address this.

**Comment by gavim6249** [comment]
My build environment is in AndroidTV 12.

I found that I need to change the package names from "tv.vizbee.system_service.service;" to "android.app" for AssistHttpServer.java, AssistService.java, and AssistServiceManager.java , Symbol _" fi.iki.elonen.NanoHTTPD"_  Import  succeed.

Then, other errors occurred (see SuppressLint.jpg).

I adding _@Nullable_ to the problematic areas resolved the errors.

In AssistServiceManager.java, an error occurred: Managers must always be obtained from Context; no direct constructors (See contextError.jpg).

**Comment by gavim6249** [comment]
![SuppressLint](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/23f915d8-2c17-4b97-8c9c-df5c5f8e01d6)

**Comment by gavim6249** [comment]
![Package](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/23ef9246-169e-437d-bd5f-8a9c2a24553b)

**Comment by gavim6249** [comment]
![ContextError](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/d4b3cf12-0b7d-4180-84b1-8da64cebadf4)

**Comment by Raasesh-Vizbee** [comment]
@gavim6249 try using package com.android.server instead of package android.app

**Comment by gavim6249** [comment]
1 I using package _"com.android.server"_ instead of package _"android.app"_
  Then, still get ...AssistHttpServer.java:20: error: symbol not found _"fi.iki.elonen.NanoHTTPD"_

2 After modify package to _"com.android.server"_
  I change java path, copy AssistHttpServer.java, AssistService.java, AssistServiceManager.java
　to **"frameworks/base/services/core/java/com/android/server/"**
　"fi.iki.elonen.NanoHTTPD" , Import succeed.....

3   Then,  frameworks/base/services/java/com/android/server/**SystemServer.java**:1014: error: cannot find symbol
 ( see ErrorSystemServer.jpg)

**Comment by gavim6249** [comment]
![ErrorSystemServer](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/8b0056e7-2fb4-4b8c-b94f-21b08f24df8a)

**Comment by Raasesh-Vizbee** [comment]
@gavim6249 remove the existing code in SystemServer. java and try with below code in 'startBootstrapServices()'

try {
       t.traceBegin("AssistService");
       mSystemServiceManager.startService(AssistService.class);
   } catch (Throwable e) {
       Slog.e(TAG, "Starting AssistService failed!!! ", e);
   }
t.traceEnd();

**Comment by gavim6249** [comment]
build completed successfully ,  Thanks

**Comment by gavim6249** [comment]
After ASSIST is running, there is a problem.

1. Starting AssistService failed!!! _( See NDS_Error1.jpg)_
2. We find problem rise in AssistSerivceManager.java
   NSD ( Network Service Discovery)  register._( See NDS_Error1.jpg)_
3. Nsd.NsdServiceInfo , **null object reference**._( See NDS_Error2.jpg)_

**Comment by gavim6249** [comment]
![NSD_Error1](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/24319e6d-bdc0-4c65-9f23-21703bd5ed01)

**Comment by gavim6249** [comment]
![NSD_Error2](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/b77374fb-982f-4c84-baed-8ca980518ca5)

**Comment by gavim6249** [comment]
[Nsd_Error.txt](https://github.com/ClaspTV/ASSIST-Service/files/12393429/Nsd_Error.txt)

**Comment by Raasesh-Vizbee** [comment]
@gavim6249, there have been updates in our code repository. Please perform the following steps:
1. Copy the modified AssistService.java and AssistServiceManager.java from the repo under system-service module and and integrate them into your codebase.
2. Please add the AssistService (Which was added to the start of startBootstrapServices() earlier) at the end of all the existing services in startOtherServices() function as mentioned in Step 5 of REAME.md file.

**Comment by gavim6249** [comment]
NSD  issue  has resolved. NSD Work successfully. (  See Nsd_OK_log.txt),  , Thanks

**Comment by gavim6249** [comment]
[Nsd_OK_log.txt](https://github.com/ClaspTV/ASSIST-Service/files/12404172/Nsd_OK_log.txt)

**Comment by shivareddy** [comment]
@gavim6249 Good to know that, Since the Service is registered, can you verify the test cases provided here https://github.com/ClaspTV/ASSIST-Service#testing

**Comment by gavim6249** [comment]
I install mDNS Discovery APK in Android Phone.
It can  find  _vzb-assist._tcp . ( See DNS_Discovery.jpg)

**Comment by gavim6249** [comment]
![DNS_APK](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/b2d4747f-4221-4645-ba8a-3258deec2de6)

**Comment by gavim6249** [comment]
![DNS_Discovery](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/2452666d-89e4-4f30-8af9-0f0530afcb0a)

**Comment by shivareddy** [comment]
@gavim6249 Good to know that. Can you also test the other cases 
https://github.com/ClaspTV/ASSIST-Service#assist-service-information-test
https://github.com/ClaspTV/ASSIST-Service#app-install-status-test

And Importantly, confirm that the Service is running and you are able to discover the ASSIST Service even hours after starting the firmware. This is to confirm the service is continuous to run until the device is powered off.

**Comment by gavim6249** [comment]
I don't have macOS, so I can't use _"dns-sd."_
Is there a way to test it on Ubuntu Linux ?
Alternatively, can I use an iPad to test  this ?

**Comment by shivareddy** [comment]
@gavim6249 
1. Please confirm you are able to discover the service `_vzb-assist._tcp.` even after 10 mins of firmware started, this is to ensure the service is continuing to run until the device is powered off.
2. Since you are able to find the service using `mDNS Discovery`, you don't need `dns-sd` command.
3. To verify the following app install status tests you need to use the Curl commands with the IP Address and Port shown in the `mDNS Discovery` app. Eg., from the above screenshot you posted the IP is 192.168.1.155 and the Port is 34011.
  ```
 Test 1: curl 192.168.1.155/34011/appInstallationStatus?packageName=com.fng.foxnation
  Test 2: curl -X POST -H "Content-Type: application/json" -d '{"packageName":{com.fng.foxnation}}' 192.168.1.155/34011/launchPlayStore
```
   
https://github.com/ClaspTV/ASSIST-Service#app-install-status-test

Confirming the service is discoverable even after 10 minutes and running the app install status tests helps us close the issue.

**Comment by gavim6249** [comment]
I try in  Ubuntu Linux,
1. App Install Status Test : Show _{"state":"App Not Installed"}_, Test pass.
2. Launch PlayStore for App Test : Show _{"state":"Success"}_, Test pass.
Please see picture _AppTest1.jpg, PlayStoreAppTest.jpg_

**Comment by gavim6249** [comment]
![AppTest1](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/5b4bb202-b75e-4a93-b963-4b7826c43dea)

**Comment by gavim6249** [comment]
![PlayStoreAppTest](https://github.com/ClaspTV/ASSIST-Service/assets/38341839/626ec493-90b0-45f6-99c1-330bc4465ef2)

**Comment by shivareddy** [comment]
@gavim6249 Good to know that. One last step
Please confirm you are able to discover the service _vzb-assist._tcp. even after 10 minutes of firmware started, this is to ensure the service is continuing to run as long as the system is up and running. Also, confirm the app install status after 10 minutes of firmware started running.

**Comment by gavim6249** [comment]
Yes, after check, We can discover the service _vzb-assist._tcp. even after 10 minutes of TV Box firmware started,
Yes, the app  can install  after 10 minutes of Tv Box firmware started running.

**Comment by maxqper** [comment]
Great. We will close this issue.
